name: deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Unit tests
        run: yarn run test:unit --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: .coverage/clover.xml

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTAL_SPACEX }}"
          channelId: live
          projectId: portal-spacex
